<a href="https://colab.research.google.com/github/alpish0510/Pytorch_play/blob/main/DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np


## Tensors

In [17]:
tens_2d=torch.zeros(2,2) # a 2d tensor (2x2 matrix)
tens_3d=torch.zeros(3,3,3) # a 3d tensor
tens_2d,tens_3d

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]))

In [25]:
## Converting a numpy array to a tensor
arr=np.random.rand(3,3)
print(arr)

tens_from_arr=torch.tensor(arr)
#tens_from_arr=torch.Tensor(arr)  # Using this, the tensor is float32 dtype
print(tens_from_arr)

[[0.32305566 0.15102017 0.06692667]
 [0.07721004 0.76222954 0.39757306]
 [0.72738645 0.23915217 0.79537248]]
tensor([[0.3231, 0.1510, 0.0669],
        [0.0772, 0.7622, 0.3976],
        [0.7274, 0.2392, 0.7954]], dtype=torch.float64)


In [27]:
tens_from_arr.dtype

torch.float64

### Tensor Operations

In [42]:
# make a tensor
tens=torch.arange(50)
tens


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
# reshaping
tens.reshape(5,10) # if one knows the shape of the tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
tens.reshape(2,-1),tens.reshape(-1,5) # if one doesn't know the exact shape, use -1.

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
          43, 44, 45, 46, 47, 48, 49]]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]))

In [48]:
## using view
tens.view(2,25)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
         43, 44, 45, 46, 47, 48, 49]])

In [53]:
## example slicing
print(tens.view(2,25)[:,1])

print(tens.reshape(-1,5)[:,2]) ## gives the numbers as a 1D tensor
print(tens.reshape(-1,5)[:,2:]) ## keeps the shape of the tensor conserved


tensor([ 1, 26])
tensor([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])
tensor([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19],
        [22, 23, 24],
        [27, 28, 29],
        [32, 33, 34],
        [37, 38, 39],
        [42, 43, 44],
        [47, 48, 49]])
